/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as SettingsRouteImport } from './../../routes/settings'
import { Route as PersonasRouteImport } from './../../routes/personas'
import { Route as ExploreRouteImport } from './../../routes/explore'
import { Route as ChatRouteImport } from './../../routes/chat'
import { Route as CharactersRouteImport } from './../../routes/characters'
import { Route as SettingsIndexRouteImport } from './../../routes/settings/index'
import { Route as ChatIndexRouteImport } from './../../routes/chat/index'
import { Route as CharactersIndexRouteImport } from './../../routes/characters/index'
import { Route as SettingsPresetsRouteImport } from './../../routes/settings/presets'
import { Route as SettingsLorebooksRouteImport } from './../../routes/settings/lorebooks'
import { Route as SettingsApiRouteImport } from './../../routes/settings/api'
import { Route as ChatIdRouteImport } from './../../routes/chat/$id'
import { Route as CharactersNewRouteImport } from './../../routes/characters/new'
import { Route as CharactersIdRouteImport } from './../../routes/characters/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CharactersRoute,
} as any)
const SettingsPresetsRoute = SettingsPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLorebooksRoute = SettingsLorebooksRouteImport.update({
  id: '/lorebooks',
  path: '/lorebooks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiRoute = SettingsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatRoute,
} as any)
const CharactersNewRoute = CharactersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CharactersRoute,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CharactersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/characters': typeof CharactersRouteWithChildren
  '/chat': typeof ChatRouteWithChildren
  '/explore': typeof ExploreRoute
  '/personas': typeof PersonasRoute
  '/settings': typeof SettingsRouteWithChildren
  '/characters/$id': typeof CharactersIdRoute
  '/characters/new': typeof CharactersNewRoute
  '/chat/$id': typeof ChatIdRoute
  '/settings/api': typeof SettingsApiRoute
  '/settings/lorebooks': typeof SettingsLorebooksRoute
  '/settings/presets': typeof SettingsPresetsRoute
  '/characters/': typeof CharactersIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/explore': typeof ExploreRoute
  '/personas': typeof PersonasRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/new': typeof CharactersNewRoute
  '/chat/$id': typeof ChatIdRoute
  '/settings/api': typeof SettingsApiRoute
  '/settings/lorebooks': typeof SettingsLorebooksRoute
  '/settings/presets': typeof SettingsPresetsRoute
  '/characters': typeof CharactersIndexRoute
  '/chat': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/characters': typeof CharactersRouteWithChildren
  '/chat': typeof ChatRouteWithChildren
  '/explore': typeof ExploreRoute
  '/personas': typeof PersonasRoute
  '/settings': typeof SettingsRouteWithChildren
  '/characters/$id': typeof CharactersIdRoute
  '/characters/new': typeof CharactersNewRoute
  '/chat/$id': typeof ChatIdRoute
  '/settings/api': typeof SettingsApiRoute
  '/settings/lorebooks': typeof SettingsLorebooksRoute
  '/settings/presets': typeof SettingsPresetsRoute
  '/characters/': typeof CharactersIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/characters'
    | '/chat'
    | '/explore'
    | '/personas'
    | '/settings'
    | '/characters/$id'
    | '/characters/new'
    | '/chat/$id'
    | '/settings/api'
    | '/settings/lorebooks'
    | '/settings/presets'
    | '/characters/'
    | '/chat/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/explore'
    | '/personas'
    | '/characters/$id'
    | '/characters/new'
    | '/chat/$id'
    | '/settings/api'
    | '/settings/lorebooks'
    | '/settings/presets'
    | '/characters'
    | '/chat'
    | '/settings'
  id:
    | '__root__'
    | '/characters'
    | '/chat'
    | '/explore'
    | '/personas'
    | '/settings'
    | '/characters/$id'
    | '/characters/new'
    | '/chat/$id'
    | '/settings/api'
    | '/settings/lorebooks'
    | '/settings/presets'
    | '/characters/'
    | '/chat/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CharactersRoute: typeof CharactersRouteWithChildren
  ChatRoute: typeof ChatRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  PersonasRoute: typeof PersonasRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/characters/': {
      id: '/characters/'
      path: '/'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/settings/presets': {
      id: '/settings/presets'
      path: '/presets'
      fullPath: '/settings/presets'
      preLoaderRoute: typeof SettingsPresetsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/lorebooks': {
      id: '/settings/lorebooks'
      path: '/lorebooks'
      fullPath: '/settings/lorebooks'
      preLoaderRoute: typeof SettingsLorebooksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api': {
      id: '/settings/api'
      path: '/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof SettingsApiRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/characters/new': {
      id: '/characters/new'
      path: '/new'
      fullPath: '/characters/new'
      preLoaderRoute: typeof CharactersNewRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof CharactersRoute
    }
  }
}

interface CharactersRouteChildren {
  CharactersIdRoute: typeof CharactersIdRoute
  CharactersNewRoute: typeof CharactersNewRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersIdRoute: CharactersIdRoute,
  CharactersNewRoute: CharactersNewRoute,
  CharactersIndexRoute: CharactersIndexRoute,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

interface ChatRouteChildren {
  ChatIdRoute: typeof ChatIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIdRoute: ChatIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsApiRoute: typeof SettingsApiRoute
  SettingsLorebooksRoute: typeof SettingsLorebooksRoute
  SettingsPresetsRoute: typeof SettingsPresetsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApiRoute: SettingsApiRoute,
  SettingsLorebooksRoute: SettingsLorebooksRoute,
  SettingsPresetsRoute: SettingsPresetsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CharactersRoute: CharactersRouteWithChildren,
  ChatRoute: ChatRouteWithChildren,
  ExploreRoute: ExploreRoute,
  PersonasRoute: PersonasRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
